---
title: "SRAG Flows"
output: html_notebook
---

## SRAG Flows in São Paulo, Brazil

```{r, warning=F, message=F}
require(dplyr)
require(igraph)
require(geobr)
require(sf)
require(ggplot2)
require(plotly)
```

```{r}
# Load Hospitalization Data
flows<-read.table(url('https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/SRAG/2021/INFLUD21-05-07-2021.csv'),sep=';',header=T,encoding='UTF-8')%>%
   filter(SG_UF_INTE=='SP'&SG_UF=='SP')%>%
   mutate(date=as.Date(DT_INTERNA,format='%D/%M/%Y'),
         age=NU_IDADE_N)

```

```{r}
# Calculate hospitalization shares
flows_count<-flows%>%
  filter(!is.na(CO_MUN_RES)&!is.na(CO_MU_INTE))%>%
  group_by(mun_res=CO_MUN_RES,mun_hosp=CO_MU_INTE)%>%
  summarize(count=n(),count_icu=sum(ifelse(UTI==1,1,0)))%>%
  mutate(share=count/sum(count),share_icu=count_icu/sum(count_icu,na.rm=T))

```
```{r message=FALSE, warning=FALSE}
# Load Shapefile
shp<-geobr::read_municipality(year=2020,showProgress=F)%>%
  filter(abbrev_state=='SP')%>%
  mutate(mun=floor(code_muni/10))%>%
  select(mun,name_muni,geom)
shp_centroid<-shp%>%
  group_by(mun)%>%
  mutate(centr=st_centroid(geom))

```
```{r}
# Network
nodes<-flows_count%>%
  data.table::melt(measure.vars=c('mun_res','mun_hosp'))%>%
  distinct(value)%>%
  dplyr::rename(mun=value)

edges<-nodes%>%rename(mun_res=mun)%>%
  merge(nodes%>%rename(mun_hosp=mun),all=T)%>%
  left_join(flows_count,by=c('mun_res','mun_hosp'))%>%
  mutate_at(.vars=c('share','share_icu'),.funs=function(x) {ifelse(is.na(x),0,x)})%>%
  rename(weight=share)

dir_net<-graph_from_data_frame(edges%>%rename(),nodes,directed=TRUE)
nodes_cluster<-nodes%>%
  mutate(cluster_fg=cluster_fast_greedy(as.undirected(dir_net))$membership,
         label=reorder(paste0('Cluster: ',cluster_fg),cluster_fg))
```

## Figure 1: SRAG Hospitalization Flows and Clusters in 2021
```{r}
# Map
  gph=ggplot(nodes_cluster%>%
               inner_join(shp,by=c('mun')),aes(text=name_muni))+
    geom_sf(aes(geometry=geom,fill=label),lwd=0.1,show.legend=F)+
    geom_sf(data=shp_centroid%>%filter(name_muni=='São Paulo')%>%ungroup,aes(geometry=centr))+
    theme_void()+
    theme(axis.line=element_blank())+
    scale_fill_manual(values=rep(RColorBrewer::brewer.pal(n=12,name='Paired'),times=10))

  plotly::ggplotly(gph,tooltip=c('text','fill'))
```
